import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import BootstrapClient from "@/app/lib/BootstrapClient"; // ✅
import ConditionalNavbar from "@/app/components/ConditionalNavbar";
import ConditionalMainWrapper from "@/app/components/ConditionalMainWrapper";
import QueryProvider from "@/app/components/QueryProvider";

import ConditionalFooter from "@/app/components/ConditionalFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  icons: {
    icon: "/public/images/logo.ico"
  },
  title: "EGYGO TRAVEL APP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BootstrapClient /> {/* Loads Bootstrap JS safely on client */}
        <QueryProvider>
          <ConditionalNavbar />
          <ConditionalMainWrapper>
            {children}
          </ConditionalMainWrapper>
          <ConditionalFooter />
        </QueryProvider>
      </body>
    </html>
  );
}
